# Generated by Django 4.0.3 on 2022-04-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0002_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=models.CharField(choices=[('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('M,L,XL', 'M,L,XL')], max_length=50),
        ),
    ]
