# Generated by Django 4.0.3 on 2022-04-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Admin', '0003_alter_products_description_alter_products_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outlets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('cell', models.CharField(max_length=12)),
                ('manager_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('map_link', models.CharField(max_length=200)),
                ('opening_hours', models.CharField(max_length=100)),
                ('closing_hours', models.CharField(max_length=100)),
                ('off_day', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='outlet_images')),
            ],
        ),
    ]
